### ISSUE TITLE
Issue about the Coming Source Code Releasing

### ISSUE THREAD

**Issue by CorgiBoyG** [HAIRLAB/inlier-identification-via-L0#2]
Thank you for your team's great work and for making important and unique contributions to the point cloud registration community. Your work minimizes the optimization problem and considers the decoupling of rotation and translation estimation. I would like to ask your team if you can publish the source code of your work. I would like to conduct comparative experiments instead of other unreasonable uses. 
Thank you again for your contribution to the point cloud registration community. Let us work together to contribute to this community. 
Thank you.

**Comment by HAIRLAB** [comment]
Thanks for your interest on our work. We are a little bit busy in these weeks and have not finished organizing the data and code. We will release the code in several weeks as soon as we have time to organize them. 
Sorry for the delay.
